# Generated by Django 6.0.1 on 2026-02-05 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', 'User Registration'), ('login', 'User Login'), ('logout', 'User Logout'), ('verify_otp', 'OTP Verification'), ('vote_cast', 'Vote Cast'), ('poll_create', 'Poll Created'), ('poll_update', 'Poll Updated'), ('poll_delete', 'Poll Deleted'), ('poll_publish', 'Poll Published'), ('candidate_add', 'Candidate Added'), ('candidate_remove', 'Candidate Removed'), ('user_block', 'User Blocked'), ('user_unblock', 'User Unblocked'), ('results_publish', 'Results Published')], max_length=50)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'), models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx')],
            },
        ),
    ]
